name: Bug Report
description: Report a bug/problem
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug/problem
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: true
